# Generated by Django 3.0 on 2021-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, max_length=2, null=True)),
                ('value', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
