# Generated by Django 3.0 on 2021-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='id',
        ),
        migrations.AlterField(
            model_name='datas',
            name='number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
