# Generated by Django 3.0 on 2021-01-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20210121_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
